# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: spark
  namespace: yarn-cluster
  labels:
    component: spark
spec:
  type: NodePort
  ports:
  - port: 7077
    name: spark
  - port: 4040
    name: ui
  # *.zeppelin.yarn-cluster.svc.cluster.local
  selector:
    component: spark
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: spark
spec:
  serviceName: "spark"
  replicas: 1
  template:
    metadata:
      labels:
        component: spark
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: spark
        image: ezalenski/arm32v7-spark:2.2.1
        ports:
          - containerPort: 4040
            name: ui
          - containerPort: 7077
            name: spark
        command:
          - "/bin/bash"
          - "/tmp/hadoop-config/bootstrap.sh"
          - "-d"
        env:
        - name: MASTER
          value: "yarn"
        - name: SPARK_SUBMIT_OPTIONS
          value: >-
            --deploy-mode client
            --num-executors 2
        resources:
          requests:
            memory: "800Mi"
            cpu: "2000m"
          limits:
            memory: "1024Mi"
            cpu: "4000m"
        volumeMounts:
          - name: hadoop-config
            mountPath: /tmp/hadoop-config
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
