# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: spark
  namespace: yarn-cluster
  labels:
    component: spark
spec:
  type: NodePort
  ports:
  - port: 7077
    name: spark
  - port: 8080
    name: web
  # *.zeppelin.yarn-cluster.svc.cluster.local
  selector:
    component: spark
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: spark
spec:
  serviceName: "spark"
  replicas: 1
  template:
    metadata:
      labels:
        component: spark
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: spark
        image: ezalenski/arm32v7-spark:2.2.1
        env:
        - name: SPARK_PORT
          value: "8080"
        - name: MASTER
          value: "yarn"
        - name: SPARK_JAVA_OPTS
          value: >-
            -Dspark.driver.memory=512m
            -Dspark.executor.memory=512m
        - name: SPARK_SUBMIT_OPTIONS
          value: >-
            --deploy-mode client
            --num-executors 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        volumeMounts:
          - name: hadoop-config
            mountPath: /usr/hadoop-2.8.2/etc/hadoop
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
